#!/bin/bash

if [ -f edge/test_cert.pem ]
then
  true
else
  ./mkcerts
fi

docker rm -f redis_eWeb_0
docker rm -f redis_eWeb_1
docker rm -f eDB_eWeb_0
docker rm -f eDB_eWeb_1
docker rm -f mongo_eWeb_0
docker rm -f mongo_eWeb_1

(sleep 30 && mongo localhost:8036/test --eval "db.items.count()") &

(go fmt ./... && cd edge && go test)
